package com.dy.huibiao_f80.greendao.daos;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dy.huibiao_f80.greendao.ProjectFGGD;
import com.dy.huibiao_f80.greendao.ProjectJTJ;
import com.dy.huibiao_f80.greendao.TestRecord;
import com.dy.huibiao_f80.greendao.Sampling;

import com.dy.huibiao_f80.greendao.daos.ProjectFGGDDao;
import com.dy.huibiao_f80.greendao.daos.ProjectJTJDao;
import com.dy.huibiao_f80.greendao.daos.TestRecordDao;
import com.dy.huibiao_f80.greendao.daos.SamplingDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig projectFGGDDaoConfig;
    private final DaoConfig projectJTJDaoConfig;
    private final DaoConfig testRecordDaoConfig;
    private final DaoConfig samplingDaoConfig;

    private final ProjectFGGDDao projectFGGDDao;
    private final ProjectJTJDao projectJTJDao;
    private final TestRecordDao testRecordDao;
    private final SamplingDao samplingDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        projectFGGDDaoConfig = daoConfigMap.get(ProjectFGGDDao.class).clone();
        projectFGGDDaoConfig.initIdentityScope(type);

        projectJTJDaoConfig = daoConfigMap.get(ProjectJTJDao.class).clone();
        projectJTJDaoConfig.initIdentityScope(type);

        testRecordDaoConfig = daoConfigMap.get(TestRecordDao.class).clone();
        testRecordDaoConfig.initIdentityScope(type);

        samplingDaoConfig = daoConfigMap.get(SamplingDao.class).clone();
        samplingDaoConfig.initIdentityScope(type);

        projectFGGDDao = new ProjectFGGDDao(projectFGGDDaoConfig, this);
        projectJTJDao = new ProjectJTJDao(projectJTJDaoConfig, this);
        testRecordDao = new TestRecordDao(testRecordDaoConfig, this);
        samplingDao = new SamplingDao(samplingDaoConfig, this);

        registerDao(ProjectFGGD.class, projectFGGDDao);
        registerDao(ProjectJTJ.class, projectJTJDao);
        registerDao(TestRecord.class, testRecordDao);
        registerDao(Sampling.class, samplingDao);
    }
    
    public void clear() {
        projectFGGDDaoConfig.clearIdentityScope();
        projectJTJDaoConfig.clearIdentityScope();
        testRecordDaoConfig.clearIdentityScope();
        samplingDaoConfig.clearIdentityScope();
    }

    public ProjectFGGDDao getProjectFGGDDao() {
        return projectFGGDDao;
    }

    public ProjectJTJDao getProjectJTJDao() {
        return projectJTJDao;
    }

    public TestRecordDao getTestRecordDao() {
        return testRecordDao;
    }

    public SamplingDao getSamplingDao() {
        return samplingDao;
    }

}
